// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML_NET_TestML.Model
{
    public class ModelInput
    {
        [ColumnName("ContactId"), LoadColumn(0)]
        public float ContactId { get; set; }


        [ColumnName("GenderCode"), LoadColumn(1)]
        public string GenderCode { get; set; }


        [ColumnName("DoNotEMail"), LoadColumn(2)]
        public float DoNotEMail { get; set; }


        [ColumnName("registration_date"), LoadColumn(3)]
        public string Registration_date { get; set; }


        [ColumnName("sendsms"), LoadColumn(4)]
        public float Sendsms { get; set; }


        [ColumnName("source"), LoadColumn(5)]
        public float Source { get; set; }


        [ColumnName("allownotification"), LoadColumn(6)]
        public float Allownotification { get; set; }


        [ColumnName("balance"), LoadColumn(7)]
        public string Balance { get; set; }


        [ColumnName("credit"), LoadColumn(8)]
        public string Credit { get; set; }


        [ColumnName("debet"), LoadColumn(9)]
        public string Debet { get; set; }


        [ColumnName("discount_summ"), LoadColumn(10)]
        public float Discount_summ { get; set; }


        [ColumnName("quantity"), LoadColumn(11)]
        public float Quantity { get; set; }


        [ColumnName("summ"), LoadColumn(12)]
        public string Summ { get; set; }


        [ColumnName("average_cheque"), LoadColumn(13)]
        public string Average_cheque { get; set; }


        [ColumnName("last_transaction_date"), LoadColumn(14)]
        public string Last_transaction_date { get; set; }


        [ColumnName("churn_bool"), LoadColumn(15)]
        public float Churn_bool { get; set; }


        [ColumnName("has_last_week_transaction"), LoadColumn(16)]
        public float Has_last_week_transaction { get; set; }


        [ColumnName("has_last_month_transaction"), LoadColumn(17)]
        public float Has_last_month_transaction { get; set; }


        [ColumnName("has_last_halfyear_transaction"), LoadColumn(18)]
        public float Has_last_halfyear_transaction { get; set; }


        [ColumnName("churn_prob"), LoadColumn(19)]
        public float Churn_prob { get; set; }


    }
}
