// This file was auto-generated by ML.NET Model Builder. 

using System;
using ML_NET_TestML.Model;

namespace ML_NET_TestML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                GenderCode = @"NULL",
                DoNotEMail = 0F,
                Sendsms = 1F,
                Allownotification = 0F,
                Credit = @"94 002,31",
                Debet = @"94 002,31",
                Discount_summ = 0F,
                Quantity = 3F,
                Summ = @"58 444,33",
                Has_last_week_transaction = 0F,
                Has_last_month_transaction = 0F,
                Has_last_halfyear_transaction = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Churn_prob with predicted Churn_prob from sample data...\n\n");
            Console.WriteLine($"GenderCode: {sampleData.GenderCode}");
            Console.WriteLine($"DoNotEMail: {sampleData.DoNotEMail}");
            Console.WriteLine($"Sendsms: {sampleData.Sendsms}");
            Console.WriteLine($"Allownotification: {sampleData.Allownotification}");
            Console.WriteLine($"Credit: {sampleData.Credit}");
            Console.WriteLine($"Debet: {sampleData.Debet}");
            Console.WriteLine($"Discount_summ: {sampleData.Discount_summ}");
            Console.WriteLine($"Quantity: {sampleData.Quantity}");
            Console.WriteLine($"Summ: {sampleData.Summ}");
            Console.WriteLine($"Has_last_week_transaction: {sampleData.Has_last_week_transaction}");
            Console.WriteLine($"Has_last_month_transaction: {sampleData.Has_last_month_transaction}");
            Console.WriteLine($"Has_last_halfyear_transaction: {sampleData.Has_last_halfyear_transaction}");
            Console.WriteLine($"\n\nPredicted Churn_prob: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
